backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
  media_folder: "_site/assets/images"
  public_folder: "assets/images/"

  collections:
  - name: 'sliderImages'
    label: 'Slider Images'
    folder: 'assets/images'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Image', name: 'image', widget: 'image' }