backend:
  name: git-gateway
  branch: main 
media_folder: "public/assets/blog" # Media files will be stored in the repo under static/images/uploads
public_folder: "/assets/blog"
collections:
 - name: "sliderImages"
   label: "slider Images"
   folder: "src/assets/images"
   create: true
   slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
   fields:
      - {label: "Image", name: "name", widget: "image"}
      